version: "3.9"
services:
  python:
    container_name: python
    build:
      context: ./python
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./python/requirements:/requirements
      - ./python/modules:/home/pythonuser/modules
      - ./python/scripts:/home/pythonuser/scripts
      - ./python/tests:/home/pythonuser/tests
      - ./python/pytest.ini:/home/pythonuser/pytest.ini
    ports:
      - 10001:10001
    networks:
      - development

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./web/src:/home/nodeuser/src
      - ./web/package-lock.json:/home/nodeuser/package-lock.json
      - ./web/package.json:/home/nodeuser/package.json
      - ./web/tsconfig.json:/home/nodeuser/tsconfig.json
      - ./web/webpack.config.js:/home/nodeuser/webpack.config.js
    ports:
      - 10000:10000
    networks:
      - development

  postgres:
    # https://hub.docker.com/_/postgres
    container_name: postgres
    image: postgres:latest
    profiles:
      - postgres
    ports:
      - 5432:5432
    environment:
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # volumes:
    #   - ./databases/init_postgres:/docker-entrypoint-initdb.d
    networks:
      - development
      
  mariadb:
    # https://hub.docker.com/_/mariadb
    container_name: mariadb
    profiles:
      - mariadb
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      # - MARIADB_RANDOM_ROOT_PASSWORD=true
      # - MARIADB_USER=${DB_USER}
      # - MARIADB_PASSWORD=${DB_PASSWORD}      
    ports:
      - 3306:3306
    # volumes:
    #   - ./databases/init_mariadb:/docker-entrypoint-initdb.d
    networks:
      - development

networks:
  development:
    name: development
    driver: bridge