version: "3.9"
services:
  python:
    container_name: cea_python
    build:
      context: ./python
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./python/requirements:/requirements
      - ./python/lib:/home/pythonuser/lib
      - ./python/bin:/home/pythonuser/bin
    ports:
      - 10001:10001

  node:
    container_name: cea_node
    build:
      context: ./web
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./web/src:/home/nodeuser/src
      - ./web/package-lock.json:/home/nodeuser/package-lock.json
      - ./web/package.json:/home/nodeuser/package.json
      - ./web/tsconfig.json:/home/nodeuser/tsconfig.json
      - ./web/webpack.config.js:/home/nodeuser/webpack.config.js
    ports:
      - 10000:10000

  postgres:
    container_name: cea_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=${FE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    # volumes:
      # - ./databases/init_postgres:/docker-entrypoint-initdb.d
